config/routes.rb
Rails.application.routes.draw do

  mount MagicLamp::Genie, at: "/magic_lamp" if defined?(MagicLamp)

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}

  get 'ajax-auth', to: 'static_pages#ajax_login'

  resources :users do
    get 'palettes', to: 'palettes#user_index'
    resources :palettes, except: [:show, :index, :create, :new, :destroy]
    resources :galleries, only: [:index], to: 'galleries#user_index'
  end

  resources :galleries, only: [:show, :index, :create]
  resources :palettes, only: [:show, :index, :create, :new, :destroy] do
    member do
      get 'new_color', as: 'new_color'
      post 'create_color', as: 'create_color'
      delete 'delete_color', as: 'delete_color'
    end
  end

  resources :pictures, only: [:destroy, :create, :update] do
    member do
      get 'editor', to: 'pictures#edit', as: 'edit'
      get '(:size)', to: 'pictures#show', as: 'show'
    end
  end

  resources :snapshots, only: [:show, :destroy]

  namespace :admin do
    resources :users, only: [:index, :show]
    resources :activities, only: [:index]
  end

  get 'admin/activity/:period/:timestamp', to: 'admin/activities#show', as: 'admin_activity'

  get 'admin', to: 'admin/activities#index'

  get 'editor', to: 'static_pages#editor'

  get 'faq', to: 'static_pages#faq'

  root to: redirect('/editor')

  get '/*foo', to: redirect('/editor')

end

app/models/palette.rb
class Palette < ActiveRecord::Base

  belongs_to :user

  validates :name, :user, presence: true

  def initialize(opts = {})
    super opts
    self.colors = []
  end

end

app/controllers/palettes_controller.rb
class PalettesController < ApplicationController
  include PixelValidation
  before_action :set_palette, except: %i[index user_index new create]
  respond_to :html

  def index
    @palettes = Palette.all
  end

  def user_index
    @palettes = Palette.where(user_id: params[:user_id])
  end

  def show
    respond_to do |format|
      format.html do
      end
      format.json do
      end
    end
  end

  def new
    @palette = Palette.new
  end

  def create
    @palette = Palette.new(palette_params)
    @palette.user_id = current_user.id
    if @palette.save
      redirect_to @palette
    else
      redirect_to palettes_path, notice: 'Palette save failed.'
    end
  end

  def destroy
    (head :unauthorized) && return unless @palette.user_id == current_user.id
    palette_name = @palette.name
    @palette.destroy
    redirect_to user_palettes_path(current_user), notice: "Palette '#{palette_name}' was deleted."
  end

  def new_color
    (head :unauthorized) && return unless @palette.user_id == current_user.id
  end

  def create_color
    (head :unauthorized) && return unless @palette.user_id == current_user.id
    @new_color = { 'r' => params[:r].to_i, 'g' => params[:g].to_i, 'b' => params[:b].to_i, 'a' => params[:a].to_i }
    (head :bad_request) && return unless rgba_valid? @new_color
    @palette.colors << @new_color
    @palette.save!
    respond_to do |format|
      format.html do
        redirect_to @palette
      end
      format.json do
        render :create_color
      end
    end
  end

  def delete_color
    (head :unauthorized) && return unless @palette.user_id == current_user.id
    removed_color = { 'r' => params[:r].to_i, 'g' => params[:g].to_i, 'b' => params[:b].to_i, 'a' => 1 }
    (head :bad_request) && return unless rgba_valid? removed_color
    @palette.colors.reject! { |color| color == removed_color }
    @palette.save!
    redirect_to @palette
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_palette
      @palette = Palette.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def palette_params
      params.require(:palette).permit(:name)
    end

end

app/views/palettes/_color_bubble.html.haml
.color_bubble{ style: "background: rgb(#{color['r']},#{color['g']},#{color['b']})" }
  #{color['r']},#{color['g']},#{color['b']}

app/views/palettes/_delete_color_link.html.haml
.remove_color_link
  - color_identifier = { r: color['r'], g: color['g'], b: color['b'], a: color['a'] }
  = link_to 'Remove Color', delete_color_palette_path(color_identifier),
                            method: :delete,
                            data: { confirm: 'Are you sure?' }

app/views/palettes/_form.html.haml
= simple_form_for @palette do |f|
  = f.input  :name
  = f.button :submit

app/views/palettes/_form_for_color.html.haml
= form_tag create_color_palette_path, method: 'post' do
  = label_tag :r, 'R:'
  = text_field_tag :r
  %br
  = label_tag :g, 'G:'
  = text_field_tag :g
  %br
  = label_tag :b, 'B:'
  = text_field_tag :b
  %br
  = hidden_field_tag :a, '1'
  = submit_tag 'Create Color'

app/views/palettes/_palette_colors_blocks.html.haml
- if palette.colors
  .colors_block.clearfix
    - palette.colors.each do |color|
      .color_entry{ style: "background: rgb(#{color['r']},#{color['g']},#{color['b']})" }

app/views/palettes/index.html.haml
%h1
  Listing palettes

#notice
  = notice

%br

- @palettes.each do |palette|

  %h1
    = link_to palette.name, palette_path(palette)

  = render 'palette_colors_blocks', palette: palette

  %br
  %br

app/views/palettes/new.html.haml
New Palette Page

= render 'form'

app/views/palettes/new_color.html.haml
#notice
  = notice

%h1
  = @palette.name

.color_bubbles.clearfix
  - if @palette.colors
    - @palette.colors.each do |color|
      .color_and_delete_link_holder
        = render 'color_bubble', color: color
        - if current_palette_owner
          = render 'palettes/delete_color_link', color: color

%br

#color_form
  = render 'form_for_color'

%br

= link_to 'Back to Index', palettes_path
- if current_palette_owner
  :preserve
     |
  = link_to 'Delete Palette', @palette, method: :delete, data: { confirm: 'Are you sure?' }

app/views/palettes/show.html.haml
#notice
  = notice

%h1
  = @palette.name

.color_bubbles.clearfix
  - if @palette.colors
    - @palette.colors.each do |color|
      .color_and_delete_link_holder
        = render 'color_bubble', color: color
        - if current_palette_owner
          = render 'palettes/delete_color_link', color: color

%br
%br

- if current_palette_owner
  = link_to 'Add New Color', new_color_palette_path, id: 'new_color_link'
  :preserve
     |
  = link_to 'Back to My Palettes', user_palettes_path(current_user)
  :preserve
     |
  = link_to 'Delete Palette', @palette, method: :delete, data: { confirm: 'Are you sure?' }
- else
  = link_to 'Back to Palettes', palettes_path

app/views/palettes/user_index.html.haml
%h1
  Listing palettes

#notice
  = notice

%br

- @palettes.each do |palette|

  %h1
    = link_to palette.name, palette_path(palette)

  = render 'palette_colors_blocks', palette: palette

  %br
  %br
%br
%br
- if user_signed_in?
  = link_to 'New Palette', new_palette_path