config/routes.rb
Rails.application.routes.draw do

  mount MagicLamp::Genie, at: "/magic_lamp" if defined?(MagicLamp)

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}

  get 'ajax-auth', to: 'static_pages#ajax_login'

  resources :users do
    get 'palettes', to: 'palettes#user_index'
    resources :palettes, except: [:show, :index, :create, :new, :destroy]
    resources :galleries, only: [:index], to: 'galleries#user_index'
  end

  resources :galleries, only: [:show, :index, :create]
  resources :palettes, only: [:show, :index, :create, :new, :destroy] do
    member do
      get 'new_color', as: 'new_color'
      post 'create_color', as: 'create_color'
      delete 'delete_color', as: 'delete_color'
    end
  end

  resources :pictures, only: [:destroy, :create, :update] do
    member do
      get 'editor', to: 'pictures#edit', as: 'edit'
      get '(:size)', to: 'pictures#show', as: 'show'
    end
  end

  resources :snapshots, only: [:show, :destroy]

  namespace :admin do
    resources :users, only: [:index, :show]
    resources :activities, only: [:index]
  end

  get 'admin/activity/:period/:timestamp', to: 'admin/activities#show', as: 'admin_activity'

  get 'admin', to: 'admin/activities#index'

  get 'editor', to: 'static_pages#editor'

  get 'faq', to: 'static_pages#faq'

  root to: redirect('/editor')

  get '/*foo', to: redirect('/editor')

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user
  belongs_to :gallery
  has_many :snapshots

  validates :user, :gallery, presence: true
  validates_format_of :name, with: /\A[a-z0-9_]+\z/i

  scope :created_between, ->(start_date, end_date) { where(created_at: start_date..end_date) }

  def current_version
    return snapshots.max_by(&:created_at)
  end

  def editor_json
    snapshot = current_version
    json = {}
    json[:picture_name] = name
    json[:cell_size] = snapshot.cell_size
    json[:picture_id] = id
    json[:pixels] = snapshot.pixels
    json[:palette_id] = palette_id
    return json
  end

  def branch(current_user)
    pic = Picture.create
    pic.name = name
    pic.user = current_user
    pic.gallery = current_user.galleries[0]
    new_snapshot = current_version.branch
    new_snapshot.picture_id = pic.id
    pic.current_version = new_snapshot
    pic.save!
    return pic
  end

  def add_snapshot(params)
    # rubocop:disable Style/GuardClause
    unless current_version && pixels_same(params[:pixels], current_version.pixels)
      snapshots.build(pixels: params[:pixels], cell_size: params[:cell_size])
    end
    # rubocop:enable Style/GuardClause
  end

  def pixels_same(foo, bar)
    return false unless foo.size == bar.size
    foo.each_with_index do |row, x|
      row.each_with_index do |_column, y|
        return false unless pixel_equal(foo[x][y], bar[x][y])
      end
    end
    return true
  end

  def pixel_equal(x, y)
    { r: x['r'].to_i, g: x['g'].to_i, b: x['b'].to_i, a: x['a'].to_i } ==
      { r: y['r'].to_i, g: y['g'].to_i, b: y['b'].to_i, a: y['a'].to_i }
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  include PixelValidation
  include StringValidation

  before_action :set_picture, only: %i[show update destroy edit]

  def show
    respond_to do |format|
      format.html do
        @picture_id = @picture.id
        @current_user_id = current_user.try(:id)
      end
      format.json { render json: @picture.editor_json }
      format.png do
        (head :bad_request) && return unless @picture
        send_data @picture.current_version.get_png(params[:size]), type: 'image/png', disposition: 'inline'
      end
    end
  end

  def destroy
    (head :unauthorized) && return unless @picture.user == current_user
    picture_gallery = @picture.gallery
    @picture.destroy
    redirect_to gallery_path(picture_gallery)
  end

  def create
    (head :bad_request) && return unless pixels_valid? params[:pixels]
    (head :unauthorized) && return unless current_user

    picture = Picture.new
    picture.name = massage_name params[:name]
    picture.palette_id = params[:palette_id]
    picture.user_id = current_user.id
    picture.gallery = current_user.galleries[0]
    picture.add_snapshot(params) if params[:pixels]
    picture.save!

    render json: {
      message: 'Picture creation success',
      status: 200,
      picture_id: picture.id,
      picture_name: picture.name
    }, status: 200
  end

  def edit
    @user_id = current_user.try(:id)
    @picture_id = @picture.id

    default_palettes = Palette.where(is_default: true)
    user_palettes = Palette.where(user_id: @user_id)
    @palettes = (default_palettes + user_palettes).uniq

    redirect_to editor_path, picture_id: @picture_id if @picture.user != current_user
  end

  def update
    (head :unauthorized) && return unless @picture.user == current_user
    @picture.name = massage_name(params[:name]) if params[:name]
    @picture.palette_id = params[:palette_id] if params[:palette_id]
    if params[:pixels]
      (head :bad_request) && return unless pixels_valid? params[:pixels]
      @picture.add_snapshot(params)
    end
    @picture.save!
    render json: {
      message: 'Picture update success',
      picture_name: @picture.name,
      status: 200
    }, status: 200
  end

  private
    def set_picture
      @picture = Picture.find(params[:id])
    end

    def picture_params
      params[:picture].permit(:name)
    end

end

app/views/pictures/_picture_thumbnail.html.haml
.thumbnail_entry
  = link_to picture_path picture do
    = image_tag picture.current_version.thumbnail_png.to_data_url, class: 'picture_thumbnail'
    %br
    = picture.name

app/views/pictures/edit.html.haml
= render 'editor/editor'

app/views/pictures/show.html.haml
#display_entry{ data: { picture_id: @picture_id } }
  = image_tag @picture.current_version.display_png.to_data_url, class: 'picture_display'

  .picture_info
    %span Picture name:
    %span#picture_name_display= @picture.name
    - if @current_user_id == @picture.user.id
      %button#change_picture_name_button Change Name
    %br
    Width: #{@picture.current_version.original_png.width}
    %br
    Height: #{@picture.current_version.original_png.height}

    %br
    %br
    = link_to 'Download at original size',
      picture_path(@picture.id, format: :png, size: :original)
    %br
    = link_to 'Download at display size (512 x 512)',
      picture_path(@picture.id, format: :png, size: :display)
    %br
    = link_to 'Download at thumbnail size (128 x 128)',
      picture_path(@picture.id, format: :png, size: :thumbnail)
    %br

    %br
    = link_to 'Edit Picture In Painter', edit_picture_path(@picture.id)
    - if @picture.user == current_user
      = button_to 'Delete Picture', { action: 'destroy', id: @picture.id },
          method: :delete, data: { confirm: 'Are you sure you want to destroy this picture?' }
  .clearfix
  - @picture.snapshots.reverse.each do |snapshot|
    = render 'snapshots/snapshot_thumbnail', snapshot: snapshot
%br