config/routes.rb
Rails.application.routes.draw do

  mount MagicLamp::Genie, at: "/magic_lamp" if defined?(MagicLamp)

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}

  get 'ajax-auth', to: 'static_pages#ajax_login'

  resources :users do
    get 'palettes', to: 'palettes#user_index'
    resources :palettes, except: [:show, :index, :create, :new, :destroy]
    resources :galleries, only: [:index], to: 'galleries#user_index'
  end

  resources :galleries, only: [:show, :index, :create]
  resources :palettes, only: [:show, :index, :create, :new, :destroy] do
    member do
      get 'new_color', as: 'new_color'
      post 'create_color', as: 'create_color'
      delete 'delete_color', as: 'delete_color'
    end
  end

  resources :pictures, only: [:destroy, :create, :update] do
    member do
      get 'editor', to: 'pictures#edit', as: 'edit'
      get '(:size)', to: 'pictures#show', as: 'show'
    end
  end

  resources :snapshots, only: [:show, :destroy]

  namespace :admin do
    resources :users, only: [:index, :show]
    resources :activities, only: [:index]
  end

  get 'admin/activity/:period/:timestamp', to: 'admin/activities#show', as: 'admin_activity'

  get 'admin', to: 'admin/activities#index'

  get 'editor', to: 'static_pages#editor'

  get 'faq', to: 'static_pages#faq'

  root to: redirect('/editor')

  get '/*foo', to: redirect('/editor')

end

app/controllers/admin/activities_controller.rb
module Admin
  class ActivitiesController < ApplicationController
    layout 'admin'

    before_action :admin_authorize

    def index
      Groupdate.time_zone = 'UTC'

      users_created_daily = User.group_by_day(:created_at, last: 7).count
      users_created_weekly = User.group_by_week(:created_at, last: 4).count
      users_created_monthly = User.group_by_month(:created_at, last: 6).count

      snapshots_created_daily = Snapshot.group_by_day(:created_at, last: 7).count
      snapshots_created_weekly = Snapshot.group_by_week(:created_at, last: 4).count
      snapshots_created_monthly = Snapshot.group_by_month(:created_at, last: 6).count

      @created_daily = users_created_daily.map do |users_count|
        [users_count.first, users_count.last, snapshots_created_daily[users_count.first]]
      end.reverse
      @created_weekly = users_created_weekly.map do |users_count|
        [users_count.first, users_count.last, snapshots_created_weekly[users_count.first]]
      end.reverse
      @created_monthly = users_created_monthly.map do |users_count|
        [users_count.first, users_count.last, snapshots_created_monthly[users_count.first]]
      end.reverse
    end

    def show
      timestamp = params[:timestamp].to_datetime
      if params[:period] == 'month'
        @time_identifier = "in #{timestamp.strftime('%B')}"
        @users = User.where(created_at: timestamp.beginning_of_month..timestamp.end_of_month)
        @pictures = Picture.where(snapshot_updated_at: timestamp.beginning_of_month..timestamp.end_of_month).includes(:snapshots, :user)
      elsif params[:period] == 'week'
        @time_identifier = "the week of #{timestamp.strftime('%m/%d')}"
        @users = User.where(created_at: (timestamp.beginning_of_week..timestamp.end_of_week))
        @pictures = Picture.where(snapshot_updated_at: timestamp.beginning_of_week..timestamp.end_of_week).includes(:snapshots, :user)
      else
        @time_identifier = "#{timestamp.strftime('%A')} the #{timestamp.day.ordinalize}"
        @users = User.where(created_at: (timestamp.beginning_of_day..timestamp.end_of_day))
        @pictures = Picture.where(snapshot_updated_at: timestamp.beginning_of_day..timestamp.end_of_day).includes(:snapshots, :user)
      end
    end

  end
end

app/views/admin/activities/_admin_picture_thumbnail.html.haml
.thumbnail_entry
  = link_to picture_path picture do
    = image_tag picture.current_version.thumbnail_png.to_data_url, class: 'picture_thumbnail'
  %br
  = link_to "User: #{picture.user.email}", admin_user_path(picture.user.id)
  %br
  = link_to "Picture: #{picture.name}", show_picture_path(picture)

app/views/admin/activities/index.html.haml
%table.snapshots_created_count_table
  %tr
    %th
      Day
    %th
      Users Created
    %th
      Snapshots Created
  - @created_daily.each do |counts|
    %tr
      %td
        = link_to "#{counts[0].strftime('%A')} the #{counts[0].day.ordinalize}",
                  admin_activity_path(:day, counts[0])
      %td
        = counts[1]
      %td
        = counts[2]
%br
%table
  %tr
    %th
      Week
    %th
      Users Created
    %th
      Snapshots Created
  - @created_weekly.each do |counts|
    %tr
      %td
        = link_to counts[0].strftime('%m/%d'), admin_activity_path(:week, counts[0])
      %td
        = counts[1]
      %td
        = counts[2]
%br
%table
  %tr
    %th
      Month
    %th
      Users Created
    %th
      Snapshots Created
  - @created_monthly.each do |counts|
    %tr
      %td
        = link_to counts[0].strftime('%B'), admin_activity_path(:month, counts[0])
      %td
        = counts[1]
      %td
        = counts[2]

app/views/admin/activities/show.html.haml
%strong Users created
%strong= @time_identifier
%br
- @users.each do |user|
  = link_to user.name, admin_user_path(user)
  %br
%br

%strong Updated pictures:
%br
- @pictures.each do |picture|
  = render 'admin_picture_thumbnail', picture: picture