config/routes.rb
Rails.application.routes.draw do

  mount MagicLamp::Genie, at: "/magic_lamp" if defined?(MagicLamp)

  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}

  get 'ajax-auth', to: 'static_pages#ajax_login'

  resources :users do
    get 'palettes', to: 'palettes#user_index'
    resources :palettes, except: [:show, :index, :create, :new, :destroy]
    resources :galleries, only: [:index], to: 'galleries#user_index'
  end

  resources :galleries, only: [:show, :index, :create]
  resources :palettes, only: [:show, :index, :create, :new, :destroy] do
    member do
      get 'new_color', as: 'new_color'
      post 'create_color', as: 'create_color'
      delete 'delete_color', as: 'delete_color'
    end
  end

  resources :pictures, only: [:destroy, :create, :update] do
    member do
      get 'editor', to: 'pictures#edit', as: 'edit'
      get '(:size)', to: 'pictures#show', as: 'show'
    end
  end

  resources :snapshots, only: [:show, :destroy]

  namespace :admin do
    resources :users, only: [:index, :show]
    resources :activities, only: [:index]
  end

  get 'admin/activity/:period/:timestamp', to: 'admin/activities#show', as: 'admin_activity'

  get 'admin', to: 'admin/activities#index'

  get 'editor', to: 'static_pages#editor'

  get 'faq', to: 'static_pages#faq'

  root to: redirect('/editor')

  get '/*foo', to: redirect('/editor')

end

app/views/layouts/admin.html.haml
- content_for :navbar do
  = link_to 'Activities', admin_activities_path
  = ' - '
  = link_to 'Users', admin_users_path
  = ' - '
  = link_to 'Logout', destroy_user_session_path, method: :delete

= render template: 'layouts/application'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pixel Paisan</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Molengo">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Lekton">
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body class="<%= controller_name %> <%= action_name %>" %>

  <div id="navbar">
    <% if content_for(:navbar) %>
      <%= yield :navbar %>
    <% elsif user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Sign up', new_user_registration_path %> |
      <%= link_to 'Login', new_user_session_path %>
    <% end %>
  </div>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</body>
<script>
  // (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  // (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  // m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  // })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  // ga('create', 'UA-86284998-1', 'auto');
  // ga('send', 'pageview');
</script>
</html>

app/views/layouts/user.html.haml
- content_for :navbar do
  Pixel Paisan!
  = ' - '
  = link_to 'Editor', root_path
  = ' - '
  - if user_signed_in?
    = link_to 'My Pictures', gallery_path(current_user.galleries[0])
    = ' - '
    = link_to 'My Palettes', user_palettes_path(current_user)
    = ' - '
    Logged in as
    %strong= current_user.email
    = ' - '
    = link_to 'Edit profile', edit_user_registration_path
    = ' - '
    = link_to 'Logout', destroy_user_session_path, method: :delete
  - else
    = link_to 'Sign up', new_user_registration_path
    = ' - '
    = link_to 'Login', new_user_session_path

  = ' - '
  = link_to 'FAQ', faq_path

  - if user_signed_in? && current_user.role == 'admin'
    = ' - '
    = link_to 'Admin', admin_activities_path

  - if Rails.env == 'development'
    = ' - '
    = link_to 'AJAX test page', ajax_auth_path



= render template: 'layouts/application'